default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: book_collection_development
test:
  <<: *default
  database: book_collection_test

production:
  <<: *default
  database: book_collection_production
  username: book_collection
  password: <%= ENV["BOOK_COLLECTION_DATABASE_PASSWORD"] %>
